baseURL = "https://hyphen-space.github.io/workspace/"
locale = "en-US"
title = "WireGuard peers"
publishDir = "build/site"
dataDir = "site-data"
cleanDestinationDir = true
disableKinds = ["404", "rss", "sitemap", "taxonomy", "term"]

[caches]
  [caches.assets]
    dir = ":cacheDir/assets"
